version: '3.9'

volumes:
  dbdata:

networks:
  localhost:
    driver: bridge

services:
  api:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/home/test_project
    env_file: .env
    container_name: test_project-container
    networks:
      - localhost
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: test_project-db
    ports:
      - 5433:5432
    volumes:
      - dbdata:/var/lib/postgresql
    networks:
      - localhost
